### PR TITLE
Remove Generics.Deriving.Lens

### PR DESCRIPTION
**Pull request by RyanGlScott**
`Generics.Deriving.Lens` was never really recommended for general use, and now it's messing up `doctests` on GHC 8.0, so it's high time to remove it. This also reenables `doctest` when build with GHC 8.0.

Fixes one part of #657 (#658 fixes the other part).

### CODE REVIEW

**Comment by ekmett** [comment]
I'm kind of sad to see these combinators go. They may not perform as well as the `Data` variants, but they respect the 'intended' structure much better. 

Can we reimplement them as part of `GHC.Generics.Lens`?

**Comment by RyanGlScott** [comment]
My objection to `Generics.Deriving.Lens` wasn't about performance, but rather correctness. The example [given in the `doctests`](https://github.com/ekmett/lens/blob/8fb89aeaec0be52c042ed971cb5793b45b818ce5/src/Generics/Deriving/Lens.hs#L73-L78), for instance, relied on `Char` having a `Generic` instance, which isn't going to work post-`base-4.9` (as well it shouldn't, since the ["leaves" of a datatype](https://ghc.haskell.org/trac/ghc/ticket/10512#comment:3) shouldn't have to be `Generic` instances).

Is it just a matter of the example being faulty, or do the combinators need to be rewritten?

**Comment by glguy** [comment]
That module was a weird mix of generics and typeable. If we could find a
properly typed approach I'd be in favor of the module. The previous
implementation relying on both typeable and Generic leaves wasn't fitting
into the shape of a typical Generics approach, though.

**Comment by ekmett** [comment]
For many use-cases the thing it does is the more 'correct' thing, even if it is badly documented. It is just different than what Data does. I'm more than happy to have us document clearly what the differences are in behavior, though. What it says definitely isn't sufficiently explanatory. This is often much better for things like removing 'one layer' of container from a thing.

**Comment by ekmett** [comment]
That said, the current implementation is somewhat boring. I'd hoped to eventually get around to computing a sort of hit-map like the Data.Lens code does, which would enable this to drastically improve performance.

**Comment by ekmett** [comment]
(That was what I was originally addressing with the issue.)

**Pull request merged**
