### PR TITLE
Add SurelyIxed class

### PR DESCRIPTION
**Pull request by treeowl**
This refines `Ixed` for total indexing, such as for representable
functors.

Implements #694

### CODE REVIEW

**Comment by treeowl** [comment]
Should I add the `Representable` "default"? This requires adding a direct `adjunctions` dependency (there's already an indirect one). Using this as a `Getter` should be just fine, but it's a thoroughly lousy `Setter`.

```haskell
ixSureRep :: (Representable f
             , Eq (Rep f)
             , Index (f a) ~ Rep f
             , IxValue (f a) ~ a)
          => Rep f -> Lens' (f a) a
ixSureRep e p f = p (Rep.index f e) <&> \a ->
   Rep.tabulate (\e' -> if e == e' then a else Rep.index f e')
```

**Comment by treeowl** [comment]
Another option would be to use a different `SureIndex` type family and remove the `Ixed` superclass. This would allow one type of index for partial lookups and another for total ones.

**Comment by fumieval** [comment]
I don't see how this could be useful.

**Comment by phadej** [comment]
I use similar class at work (I call it `Att` :P). It's useful for `a -> b` instance. Also I have a date `TotalMap k v { tmDef :: v, tmMap :: Map k v }`, where `Att` is useful.

I don't like `Att` neither `SurelyIxed` names. something short yet descriptive would be great.

**Comment by ekmett** [comment]
Given a general dearth of instances in the things lens depends on, I think I'm going to close this as an out of scope sort of issue. Feel free to package it somewhere independently.

**Pull request closed without merging**
