### PR TITLE
Add 'getter'

### PR DESCRIPTION
**Pull request by emilypi**
See #759

### CODE REVIEW

**Comment by phadej** [comment]
This is a synonym of `to`, isn't it?

I sympahetise the addition, I have used `getter` name in own developments

**Comment by emilypi** [comment]
@phadej yes - i could probably just point to `to` instead of expanding the statement. Would you prefer it just be `getter = to`?

**Comment by ekmett** [comment]
I'm somewhat inclined to just keep `to` as the only name for this. It is shorter, we already took it, and adding getter means more random spurious conflicts and local name shadowing complaints as it is a reasonable local name people might use locally in their own code.

**Comment by phadej** [comment]
True. I imagine there are a lot of code like

```haskell
myFancyLens = lens getter setter where
  getter = ...
  setter = ...
```

**Comment by emilypi** [comment]
Thanks @ekmett I hadn't thought of that. I guess @phadej you'll have to do wtih a local alias 😄

**Comment by emilypi** [comment]
So should we close this?

**Pull request closed without merging**
