### PR TITLE
Download hlint from GitHub instead

### LINKED ISSUE #738: Travis builds are timing out
The `lens` test suites take longer than you'd expect on Travis CI's build machines, sometimes going for periods of longer than 10 minutes (Travis's timeout limit) without any output. See [here](https://travis-ci.org/ekmett/lens/jobs/241541282#L748) for an example.

We should try using [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) to see if that eliminates the problem.

### PR DESCRIPTION
**Pull request by RyanGlScott**
There's not much point to building the whole `hlint` library (and all of its many dependencies, including `haskell-src-exts`) when in the end, all we use `hlint` for is its executable functionality. We can more easily install a prebuild `hlint` from GitHub and use that.

Fixes #738.

### CODE REVIEW

**Comment by glguy** [comment]
This seems like a good idea to me

**Comment by RyanGlScott** [comment]
Oh, right. Now I see why we're installing `hlint` from source: we need a newer version to handle some GHC extensions. From the [log for the GHC 7.6 build](https://travis-ci.org/ekmett/lens/jobs/243715528#L921):

```
$ hlint src --cpp-define=HLINT --cpp-ansi
src/Control/Exception/Lens.hs:168:13: Parse error
Error message:
  Parse error: AllocationLimitExceeded_
Code:
      -- ** Allocation Limit Exceeded
      , AsAllocationLimitExceeded(..)
  >   , pattern AllocationLimitExceeded_

src/Control/Lens/At.hs:204:3: Parse error
Error message:
  Parse error: default
Code:
      -- Nothing
      ix :: Index m -> Traversal' m (IxValue m)
  >   default ix :: (Applicative f, At m) => Index m -> LensLike' f m (IxValue m)
      ix = ixAt
      {-# INLINE ix #-}

src/Control/Lens/Each.hs:86:3: Parse error
Error message:
  Parse error: default
Code:
    class Each s t a b | s -> a, t -> b, s b -> t, t a -> s where
      each :: Traversal s t a b
  >   default each :: (Traversable g, s ~ g a, t ~ g b) => Traversal s t a b
      each = traverse
      {-# INLINE each #-}

src/Control/Lens/Empty.hs:66:3: Parse error
Error message:
  Parse error: default
Code:
      -- True
      _Empty :: Prism' a ()
  >   default _Empty :: (Monoid a, Eq a) => Prism' a ()
      _Empty = only mempty
      {-# INLINE _Empty #-}

src/Control/Lens/Indexed.hs:244:3: Parse error
Error message:
  Parse error: default
Code:
      -- | Map with access to the index.
      imap :: (i -> a -> b) -> f a -> f b
  >   default imap :: TraversableWithIndex i f => (i -> a -> b) -> f a -> f b
      imap = iover itraversed
      {-# INLINE imap #-}

src/Control/Lens/Plated.hs:221:3: Parse error
Error message:
  Parse error: default
Code:
      -- it with your own definition.
      plate :: Traversal' a a
  >   default plate :: Data a => Traversal' a a
      plate = uniplate

src/Control/Lens/Tuple.hs:103:3: Parse error
Error message:
  Parse error: default
Code:
      -- @
      _1 :: Lens s t a b
  >   default _1 :: (Generic s, Generic t, GIxed N0 (Rep s) (Rep t) a b)
                 => Lens s t a b
      _1 = ix proxyN0

Warning: Can't find file "HsBaseConfig.h" in directories
	src/Control/Lens
	.
  Asked for by: src/Control/Lens/Wrapped.hs  at line 85 col 1
src/Control/Lens/Wrapped.hs:192:3: Parse error
Error message:
  Parse error: default
Code:
Warning: Can't find file "HsBaseConfig.h" in directories
	.
  Asked for by:   at line 85 col 1
      -- and you can choose to not override it with your own definition.
      _Wrapped' :: Iso' s (Unwrapped s)
  >   default _Wrapped' :: (Generic s, D1 d (C1 c (S1 s' (Rec0 a))) ~ Rep s, Unwrapped s ~ GUnwrapped (Rep s))
                        => Iso' s (Unwrapped s)
      _Wrapped' = _GWrapped'

src/Control/Lens/Zoom.hs:200:20: Error: Use .
Found:
  liftM (fmap $ zoom l) .
    liftM getFreed .
      zoom (\ afb -> unfocusingFree #. l (FocusingFree #. afb)) .
        liftM Freed . runFreeT
Why not:
  liftM ((fmap $ zoom l) . getFreed) .
    zoom (\ afb -> unfocusingFree #. l (FocusingFree #. afb)) .
      liftM Freed . runFreeT

src/Control/Lens/Internal/TH.hs:114:1: Warning: Use camelCase
Found:
  mkLensName_tc = ...
Why not:
  mkLensNameTc = ...

src/Control/Lens/Internal/TH.hs:117:1: Warning: Use camelCase
Found:
  mkLensName_v = ...
Why not:
  mkLensNameV = ...

src/Control/Lens/Internal/TH.hs:162:1: Warning: Use camelCase
Found:
  _wrapped'ValName = ...
Why not:
  _wrappedValName = ...

12 suggestions (26 ignored)


The command "hlint src --cpp-define=HLINT --cpp-ansi" exited with 1.
```

I know at one point we surrounded a lot of code with `#ifdef HLINT ... #endif` to work around this. I'm not sure if we want to re-introduce that hack...

**Comment by phadej** [comment]
Neil provides binary builds for `hlint`, i can tell more when I get back to my PC

**Comment by phadej** [comment]
```sh
mkdir ~/.hlint
curl -L https://github.com/ndmitchell/hlint/releases/download/v2.0.9/hlint-2.0.9-x86_64-linux.tar.gz | tar -xz --strip-components=1 -C ~/.hlint
~/.hlint/hlint src
```

works on my Ubuntu

**Comment by RyanGlScott** [comment]
Ah, good point @phadej. Downloading `hlint` directly from GitHub ends up being much easier to support.

**Pull request merged**
