### PR TITLE
Use alterF for several instances in Control.Lens.At

### PR DESCRIPTION
**Pull request by sjakobi**
Note that `Set`'s instances will behave slightly differently with `containers >= 0.6.3`: When we're looking for a certain element `e`, and an equal element `e'` is found in the set, `e'` will not be replaced by `e`. This was discussed in https://github.com/ekmett/lens/issues/901.

(CC @treeowl)

### CODE REVIEW

**Comment by sjakobi** [comment]
BTW, I noticed some funny-looking `Ixed` instances and wondered whether these could be improved too:

https://github.com/ekmett/lens/blob/89b736bbbbeb6368a636fb612a07c0d0b56445d0/src/Control/Lens/At.hs#L278-L318

**Comment by treeowl** [comment]
@sjakobi, some of those should be improvable; some of them are probably less so. It's really hard to do better than the naive thing for `IntMap`, by which I mean I don't know of a way. For `HashMap`, the biggest thing is to avoid calculating the hash twice; that needs some access to the internals unless we add an `adjustF` function.

**Comment by sjakobi** [comment]
Thanks @treeowl! I'll leave `Ixed` for future work until we've resolved https://github.com/haskell-unordered-containers/unordered-containers/issues/211 then.

@phadej Should I make an issue to record this plan?

**Comment by sjakobi** [comment]
Superseded by https://github.com/ekmett/lens/pull/962 and https://github.com/ekmett/lens/pull/963.

**Pull request closed without merging**
