### PR TITLE
Port .travis.yml over to new-build, and vendor in doctest

### PR DESCRIPTION
**Pull request by RyanGlScott**
This should make the build more robust and (hopefully) prevent the tests from timing out on Travis.

Supersedes #646. Addresses one point of #738.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Bah. Either I did something wrong, or something fishy is happening, since the [doctests are timing out](https://travis-ci.org/ekmett/lens/jobs/242258715#L1324) even after this change...

**Comment by glguy** [comment]
The default hvr .travis.yml overwrites your cabal.project

https://github.com/RyanGlScott/lens/blob/baea18f3bb2915c656526ce4bf81b99dfcf1eb38/.travis.yml#L84

**Comment by RyanGlScott** [comment]
Ack, I deleted one occurrence of that in the default script, but I didn't see that other one! Let's see what happens after I delete _that_ one...

**Comment by glguy** [comment]
I believe that the problem is that the build script tests building an sdist, which isn't including the vendored doctest!

**Comment by RyanGlScott** [comment]
Oy vey. This is what I get for blindly trusting an autogenerated script...

Take three.

**Comment by glguy** [comment]
Is it necessary to build lens twice, we're doing that once with tests disabled and again with them enabled. It just takes 2x as long to do that, right?

**Comment by glguy** [comment]
In my tests GHC 7.6.3 appears to tickle the bug that doctest was working around https://travis-ci.org/ekmett/lens/builds/242294540

**Comment by RyanGlScott** [comment]
We're not actually building the entirety of `lens` twice, since it caches the result of the previous build (without tests and benchmarks).

That being said, it does seem a bit odd to build it in stages like that. I do prefer the old behavior better, where we build the library, tests, and benchmarks all at once, and then run the tests immediately afterwards. If this build succeeds, I'll do that consolidation step next.

**Comment by glguy** [comment]
I watched it slowly build it again, (configuration changed) was cited as the reason, and it was just as slow the second time

**Comment by RyanGlScott** [comment]
Oh, this must be a GHC-specific thing. On [this GHC 8.2.1 run](https://travis-ci.org/ekmett/lens/jobs/242294541), it doesn't exhibit that behavior, but on [this GHC 7.6.3 run](https://travis-ci.org/ekmett/lens/jobs/242294545), it does. Disturbing...

**Comment by RyanGlScott** [comment]
> In my tests GHC 7.6.3 appears to tickle the bug that doctest was working around https://travis-ci.org/ekmett/lens/builds/242294540

Argh, and I had boldly proclaimed that this bug wasn't present anymore in https://github.com/sol/doctest/issues/164#issuecomment-307654699, too...

I suppose that this won't be the cure-all we'd hoped for, then. Any ideas for avoiding timeouts on GHC 7.6 and older?

**Comment by glguy** [comment]
Exactly two tests fail, we can delete them, change them, or CPP them

**Comment by RyanGlScott** [comment]
>Exactly two tests fail, we can delete them, change them, or CPP them

This makes me leery. If that `doctest` patch really is broken on GHC 7.4 and 7.6, then any attempts to conditionally fix tests on our end are inherently fragile. There's no telling when the bug would crop up during a modification of another test, or when introducing new ones.

I've opted to simply guard that `:reload` behind CPP for now (and fix the double-build bug you mentioned in https://github.com/ekmett/lens/pull/741#issuecomment-308017376). Let's see if the timeout happens on old GHCs.

**Comment by phadej** [comment]
The script builds also without tests enabled, because test-suites and bencmarks might (and often do) affect the exact dependencies of the library, e.g. in the case test-dependency has restrictive bound like "it depends on old optparse-applicative, and only newer optparse-applicative allows newest transformers-compat.

**Comment by RyanGlScott** [comment]
That explanation makes sense, @phadej, thanks.

Still, there's a problem that old GHCs (for instance, 7.6) are rebuilding the entire library when you run `cabal new-test` after `cabal new-build` because it thinks the configuration changed. That's pretty bad - I'd almost consider that a deal-breaker for switching over to `new-build`, even. It seems like it might be a `Cabal` bug... does anyone know what's going on here?

**Comment by RyanGlScott** [comment]
Hrm. Even with `cabal-install-head`, the duplicate-build bug is still present. That's frustrating.

**Comment by RyanGlScott** [comment]
An update. After much trial-and-error (many thanks to @hvr for the assistance!), I managed to fix (or at least work around) the double-build bug. So I can confidently state that `new-build` is `lens`-ready, which is nice.

Unfortunately, the ultimate goal of making the `doctest`s not time out is still a problem. I'm using a modified version of `doctest` here, but due to https://github.com/ekmett/lens/pull/741#issuecomment-308017962, we can't apply the speed hack to GHC 7.6 and earlier. As you might expect, this means the GHC 7.4 and 7.6 builds can time out, and this actually happened in the most recent build: https://travis-ci.org/ekmett/lens/jobs/243353190

I don't know how to work around that old `doctest` bug yet, so until I do, I propose that we run `cabal new-test` with `travis_wait`. This means that the GHC 7.4 and 7.6 builds will take longer than the others, but I think we'd still fall under the 60-minute window, which is the maximum amount of time that you can run a single Travis job for. Does that sound agreeable, @glguy?

**Comment by RyanGlScott** [comment]
Actually, it turns out that one can work around the aforementioned GHC 7.4 and 7.6 bug [quite easily](https://github.com/sol/doctest/pull/165#issuecomment-308953288), so after incorporating the fix, all builds are green! Hooray!

**Pull request merged**
