### PR TITLE
Add throwing_ to Control.Monad.Error.Lens

### PR DESCRIPTION
**Pull request by axman6**

### CODE REVIEW

**Comment by axman6** [comment]
Any chance of getting this merged? the build failures were due to something else in master at the time not this PR.

**Comment by ekmett** [comment]
No objection to the combinator. The random included formatting changes are what are holding you up. =P

**Comment by axman6** [comment]
Ha, not sure how those even made it into there! Thanks for adding it!

**Comment by ekmett** [comment]
We're slowly rounding up a release so these will probably make it out soonish.

**Pull request closed without merging**
