### PR TITLE
Demote imapped, ifolded, itraversed methods to standalone combinators

### PR DESCRIPTION
**Pull request by phadej**
This is first step towards #941

cc @arybczak, @ekmett

### CODE REVIEW

**Comment by phadej** [comment]
I also made a `with-index` (only GHC deps) and `with-index-instances` (some more stuff) packages. https://github.com/phadej/with-index See `patches` directory how that would affect `optics`, `lens` (and `free`).

**Comment by arybczak** [comment]
You might want to compare benchmarks, afaik I tried that and there were some regressions.

BTW, instances of `*WithIndex` from `optics` give better performance in some cases than the ones from `lens` - I think your `with-index` package took them from `lens`.

**Comment by phadej** [comment]
> BTW, instances of *WithIndex from optics give better performance.

Maybe. I'll be happy to review PRs to `with-index`. I guess one idea of having `with-index` is that everyone would benefit from the benchmarking & optimization work. However, I have limited time, so would like to proceed in small steps. (I have bad experiences I don't want to repeat related to languishing change proposals).

**Comment by phadej** [comment]
I incorporated the explicit instances from `optics` into `with-index`.

**Comment by phadej** [comment]
I run `optics:bench:traversals` benchmark, with current `optics` master, `optics` using `with-index`, and `optics` and `lens` using `with-index`. (The `traversals` benchmarks compares to `optics` to `lens`). The results are

```
Benchmark                              baseline-3  optics-3           optics-lens-3         
bytestring char8/imap/chars               9.77e-4   9.60e-4   -1.71%        9.58e-4   -1.93%
bytestring char8/imap/chars/lens          9.85e-4   9.67e-4   -1.80%        9.65e-4   -2.04%
bytestring char8/map/chars                4.72e-4   4.70e-4   -0.55%        4.70e-4   -0.57%
bytestring char8/map/chars/lens           4.78e-4   4.69e-4   -1.90%        4.69e-4   -1.84%
bytestring char8/map/native               4.74e-4   4.71e-4   -0.62%        4.72e-4   -0.42%
bytestring lazy char8/imap/chars          1.02e-2   9.75e-3   -4.68%        9.59e-3   -6.19%
bytestring lazy char8/imap/chars/lens     1.85e-2   1.76e-2   -4.79%        1.75e-2   -5.38%
bytestring lazy char8/map/chars           3.66e-3   3.80e-3   +4.01%        3.79e-3   +3.73%
bytestring lazy char8/map/chars/lens      1.24e-2   1.38e-2  +10.93%        1.35e-2   +9.07%
bytestring lazy char8/map/native          3.66e-3   3.80e-3   +3.89%        3.78e-3   +3.35%
bytestring lazy/imap/bytes                9.65e-3   9.77e-3   +1.25%        9.54e-3   -1.13%
bytestring lazy/imap/bytes/lens           1.80e-2   1.75e-2   -2.35%        1.74e-2   -3.05%
bytestring lazy/map/each                  2.84e-3   2.73e-3   -4.02%        2.72e-3   -4.46%
bytestring lazy/map/each/lens             4.88e-4   4.81e-4   -1.35%        4.82e-4   -1.20%
bytestring lazy/map/native                3.62e-3   3.80e-3   +4.87%        3.79e-3   +4.64%
bytestring/imap/bytes                     4.67e-5   6.94e-5  +48.56%        7.03e-5  +50.44%
bytestring/imap/bytes/lens                4.65e-5   6.92e-5  +48.80%        7.01e-5  +50.59%
bytestring/map/each                       4.84e-4   4.73e-4   -2.27%        4.73e-4   -2.13%
bytestring/map/each/lens                  4.64e-5   3.75e-5  -19.17%        3.75e-5  -19.24%
bytestring/map/native                     4.82e-4   4.70e-4   -2.33%        4.73e-4   -1.82%
hash map/elements/elements                1.66e-3   1.64e-3   -0.77%        1.64e-3   -0.90%
hash map/elements/elements/lens           2.94e-3   2.93e-3   -0.53%        2.93e-3   -0.38%
hash map/elements/itraversed              8.45e-4   8.41e-4   -0.53%        8.38e-4   -0.87%
hash map/elements/itraversed/lens         8.68e-4   8.41e-4   -3.07%        8.37e-4   -3.56%
hash map/imap/each                        8.03e-4   8.30e-4   +3.47%        8.27e-4   +3.04%
hash map/imap/imap                        8.59e-4   8.41e-4   -2.13%        8.49e-4   -1.26%
hash map/imap/imap/lens                   8.37e-4   8.43e-4   +0.76%        8.40e-4   +0.40%
hash map/imap/imapped                     8.38e-4   8.35e-4   -0.36%        8.32e-4   -0.76%
hash map/imap/imapped/lens                8.39e-4   8.34e-4   -0.52%        8.34e-4   -0.56%
hash map/imap/itraversed                  8.36e-4   8.37e-4   +0.11%        8.37e-4   +0.10%
hash map/imap/itraversed/lens             8.37e-4   8.98e-4   +7.30%        8.68e-4   +3.70%
hash map/imap/native                      4.01e-4   4.06e-4   +1.11%        3.98e-4   -0.67%
hash map/indices/indices                  7.48e-4   7.36e-4   -1.57%        7.35e-4   -1.64%
hash map/indices/indices/lens             7.92e-4   7.99e-4   +0.89%        7.82e-4   -1.27%
hash map/itraverse/each                   3.14e-3   3.26e-3   +3.80%        3.23e-3   +2.78%
hash map/itraverse/itraverse              3.18e-3   3.15e-3   -1.08%        3.24e-3   +1.85%
hash map/itraverse/itraverse/lens         3.15e-3   3.14e-3   -0.32%        3.19e-3   +1.26%
hash map/itraverse/itraversed             3.17e-3   3.28e-3   +3.16%        3.22e-3   +1.33%
hash map/itraverse/itraversed/lens        3.16e-3   3.25e-3   +2.93%        3.20e-3   +1.18%
hash map/itraverse/native                 3.06e-3   3.03e-3   -1.00%        3.08e-3   +0.56%
hash map/map/each                         7.24e-4   7.65e-4   +5.78%        7.43e-4   +2.71%
hash map/map/each/lens                    8.01e-4   8.78e-4   +9.64%        8.73e-4   +9.04%
hash map/map/imapped                      8.32e-4   8.49e-4   +2.02%        8.15e-4   -1.99%
hash map/map/imapped/lens                 8.19e-4   8.05e-4   -1.78%        8.28e-4   +1.09%
hash map/map/itraversed                   8.11e-4   8.19e-4   +0.97%        8.12e-4   +0.13%
hash map/map/itraversed/lens              8.01e-4   8.14e-4   +1.60%        8.16e-4   +1.95%
hash map/map/native                       3.73e-4   3.83e-4   +2.66%        3.83e-4   +2.57%
hash map/partsOf/ipartsOf                 3.08e-3   2.90e-3   -5.90%        2.93e-3   -5.09%
hash map/partsOf/ipartsOf/lens            1.29e-2   1.32e-2   +2.60%        1.32e-2   +2.43%
hash map/partsOf/partsOf                  2.26e-3   2.16e-3   -4.46%        2.20e-3   -2.97%
hash map/partsOf/partsOf/lens             1.37e-2   1.36e-2   -0.42%        1.36e-2   -1.09%
hash map/singular/singular                1.67e-3   1.70e-3   +1.99%        1.70e-3   +1.88%
hash map/singular/singular/lens           1.35e-2   1.35e-2   -0.14%        1.35e-2   +0.28%
hash map/traverse/each                    3.07e-3   3.06e-3   -0.30%        3.12e-3   +1.66%
hash map/traverse/each/lens               3.20e-3   3.17e-3   -0.94%        3.24e-3   +1.53%
hash map/traverse/itraversed              3.21e-3   3.16e-3   -1.41%        3.24e-3   +1.14%
hash map/traverse/itraversed/lens         3.25e-3   3.16e-3   -2.69%        3.23e-3   -0.53%
hash map/traverse/native                  3.22e-3   3.17e-3   -1.49%        3.22e-3   +0.18%
intmap/elements/elements                  7.18e-4   7.10e-4   -1.16%        7.31e-4   +1.80%
intmap/elements/elements/lens             1.35e-3   1.38e-3   +2.50%        1.37e-3   +1.59%
intmap/elements/itraversed                5.12e-4   5.17e-4   +0.91%        5.19e-4   +1.32%
intmap/elements/itraversed/lens           5.08e-4   5.10e-4   +0.51%        5.13e-4   +1.04%
intmap/imap/each                          4.08e-4   4.12e-4   +1.06%        4.14e-4   +1.50%
intmap/imap/imap                          5.16e-4   5.13e-4   -0.64%        5.17e-4   +0.22%
intmap/imap/imap/lens                     5.17e-4   5.14e-4   -0.59%        5.16e-4   -0.31%
intmap/imap/imapped                       5.15e-4   5.13e-4   -0.27%        5.14e-4   -0.11%
intmap/imap/imapped/lens                  5.20e-4   5.13e-4   -1.45%        5.14e-4   -1.31%
intmap/imap/itraversed                    5.18e-4   5.15e-4   -0.69%        5.14e-4   -0.82%
intmap/imap/itraversed/lens               5.20e-4   5.12e-4   -1.48%        5.15e-4   -1.04%
intmap/imap/native                        5.15e-4   5.13e-4   -0.29%        5.15e-4   +0.05%
intmap/indices/indices                    3.22e-4   3.19e-4   -1.02%        3.28e-4   +1.97%
intmap/indices/indices/lens               5.07e-4   4.97e-4   -1.91%        4.99e-4   -1.50%
intmap/itraverse/each                     2.18e-3   2.08e-3   -4.71%        2.08e-3   -4.28%
intmap/itraverse/itraverse                2.29e-3   2.09e-3   -8.72%        2.09e-3   -8.64%
intmap/itraverse/itraverse/lens           2.18e-3   2.09e-3   -3.86%        2.15e-3   -1.14%
intmap/itraverse/itraversed               2.17e-3   2.10e-3   -3.45%        2.09e-3   -3.93%
intmap/itraverse/itraversed/lens          2.16e-3   2.08e-3   -3.73%        2.09e-3   -3.45%
intmap/itraverse/native                   2.11e-3   2.09e-3   -1.00%        2.09e-3   -1.30%
intmap/map/each                           3.72e-4   3.80e-4   +2.19%        3.77e-4   +1.31%
intmap/map/each/lens                      3.72e-4   3.78e-4   +1.63%        3.78e-4   +1.66%
intmap/map/imapped                        3.74e-4   3.78e-4   +1.04%        3.81e-4   +2.04%
intmap/map/imapped/lens                   3.78e-4   3.78e-4   -0.21%        3.79e-4   +0.19%
intmap/map/itraversed                     3.71e-4   3.77e-4   +1.66%        3.81e-4   +2.52%
intmap/map/itraversed/lens                3.73e-4   3.78e-4   +1.35%        3.81e-4   +2.15%
intmap/map/native                         3.73e-4   3.77e-4   +1.14%        3.79e-4   +1.70%
intmap/partsOf/ipartsOf                   3.59e-3   3.60e-3   +0.40%        3.64e-3   +1.30%
intmap/partsOf/ipartsOf/lens              8.21e-3   8.21e-3   -0.01%        8.28e-3   +0.77%
intmap/partsOf/partsOf                    2.65e-3   2.63e-3   -0.54%        2.65e-3   +0.10%
intmap/partsOf/partsOf/lens               1.12e-2   1.13e-2   +1.11%        1.14e-2   +1.83%
intmap/singular/singular                  1.96e-3   1.91e-3   -2.50%        1.97e-3   +0.62%
intmap/singular/singular/lens             7.26e-3   7.16e-3   -1.36%        7.24e-3   -0.33%
intmap/traverse/each                      1.64e-3   1.61e-3   -2.28%        1.60e-3   -2.55%
intmap/traverse/each/lens                 1.65e-3   1.61e-3   -2.55%        1.60e-3   -3.46%
intmap/traverse/itraversed                1.65e-3   1.63e-3   -1.02%        1.61e-3   -2.37%
intmap/traverse/itraversed/lens           1.66e-3   1.61e-3   -2.91%        1.61e-3   -3.12%
intmap/traverse/native                    1.70e-3   1.62e-3   -4.53%        1.60e-3   -5.79%
list/elements/elements                    1.88e-4   1.83e-4   -2.68%        1.83e-4   -2.56%
list/elements/elements/lens               1.50e-4   1.36e-4   -9.38%        1.36e-4   -9.19%
list/elements/itraversed                  9.94e-5   9.67e-5   -2.69%        9.72e-5   -2.22%
list/elements/itraversed/lens             1.52e-4   1.42e-4   -6.84%        1.42e-4   -6.50%
list/imap/each                            1.06e-4   9.96e-5   -5.71%        9.40e-5  -11.00%
list/imap/imap                            1.05e-4   1.00e-4   -4.67%        9.96e-5   -5.50%
list/imap/imap/lens                       1.42e-4   1.31e-4   -8.06%        1.31e-4   -8.16%
list/imap/imapped                         1.05e-4   9.51e-5   -9.69%        9.98e-5   -5.29%
list/imap/imapped/lens                    1.42e-4   1.31e-4   -7.58%        1.37e-4   -4.04%
list/imap/itraversed                      1.03e-4   9.58e-5   -7.15%        9.96e-5   -3.43%
list/imap/itraversed/lens                 1.42e-4   1.31e-4   -8.25%        1.32e-4   -7.51%
list/indices/indices                      9.91e-5   9.20e-5   -7.14%        9.20e-5   -7.20%
list/indices/indices/lens                 1.51e-4   1.39e-4   -8.39%        1.44e-4   -5.23%
list/itraverse/each                       1.08e-3   1.08e-3   -0.35%        1.08e-3   -0.49%
list/itraverse/itraverse                  1.02e-3   1.02e-3   -0.20%        1.03e-3   +0.44%
list/itraverse/itraverse/lens             1.40e-3   1.39e-3   -0.71%        1.40e-3   -0.25%
list/itraverse/itraversed                 1.04e-3   1.04e-3   -0.33%        1.04e-3   +0.15%
list/itraverse/itraversed/lens            1.41e-3   1.34e-3   -5.40%        1.34e-3   -5.45%
list/itraverse/native                     1.03e-3   1.03e-3   -0.12%        1.02e-3   -0.72%
list/map/each                             9.78e-5   1.04e-4   +6.79%        1.05e-4   +6.91%
list/map/each/lens                        9.88e-5   1.03e-4   +4.15%        1.05e-4   +5.87%
list/map/imapped                          9.83e-5   1.03e-4   +5.21%        1.05e-4   +6.63%
list/map/imapped/lens                     9.84e-5   1.05e-4   +6.28%        1.04e-4   +5.82%
list/map/itraversed                       9.88e-5   1.05e-4   +6.24%        1.05e-4   +5.94%
list/map/itraversed/lens                  9.83e-5   1.04e-4   +5.69%        1.07e-4   +9.03%
list/map/native                           9.70e-5   1.04e-4   +7.68%        1.04e-4   +7.65%
list/partsOf/ipartsOf                     1.58e-3   1.52e-3   -4.00%        1.52e-3   -3.86%
list/partsOf/ipartsOf/lens                4.74e-3   4.74e-3   -0.06%        4.73e-3   -0.14%
list/partsOf/partsOf                      4.20e-4   4.06e-4   -3.36%        4.12e-4   -1.75%
list/partsOf/partsOf/lens                 3.11e-3   3.14e-3   +0.77%        3.15e-3   +1.05%
list/singular/singular                    3.13e-4   1.82e-4  -41.80%        1.82e-4  -41.68%
list/singular/singular/lens               1.38e-3   1.37e-3   -0.23%        1.37e-3   -0.19%
list/traverse/each                        9.16e-4   9.12e-4   -0.39%        9.25e-4   +0.99%
list/traverse/each/lens                   9.13e-4   9.10e-4   -0.34%        9.23e-4   +1.09%
list/traverse/itraversed                  9.09e-4   9.16e-4   +0.81%        9.27e-4   +2.03%
list/traverse/itraversed/lens             9.13e-4   9.14e-4   +0.15%        9.24e-4   +1.21%
list/traverse/native                      9.12e-4   9.12e-4   -0.02%        9.13e-4   +0.09%
map/elements/elements                     5.09e-4   5.18e-4   +1.82%        5.40e-4   +6.06%
map/elements/elements/lens                1.47e-3   1.45e-3   -1.71%        1.48e-3   +0.33%
map/elements/itraversed                   5.58e-4   5.70e-4   +2.10%        5.70e-4   +2.08%
map/elements/itraversed/lens              5.55e-4   5.68e-4   +2.29%        5.71e-4   +2.88%
map/imap/each                             4.21e-4   4.27e-4   +1.50%        4.28e-4   +1.67%
map/imap/imap                             5.55e-4   5.69e-4   +2.40%        5.67e-4   +2.02%
map/imap/imap/lens                        5.57e-4   5.71e-4   +2.40%        5.66e-4   +1.56%
map/imap/imapped                          5.56e-4   5.65e-4   +1.57%        5.68e-4   +2.13%
map/imap/imapped/lens                     5.56e-4   5.72e-4   +2.73%        5.67e-4   +2.00%
map/imap/itraversed                       5.58e-4   5.73e-4   +2.70%        5.67e-4   +1.68%
map/imap/itraversed/lens                  5.73e-4   5.72e-4   -0.07%        5.66e-4   -1.28%
map/imap/native                           5.55e-4   5.70e-4   +2.63%        5.66e-4   +1.96%
map/indices/indices                       4.15e-4   4.14e-4   -0.13%        4.23e-4   +2.01%
map/indices/indices/lens                  5.38e-4   5.56e-4   +3.32%        5.72e-4   +6.36%
map/itraverse/each                        1.23e-3   1.20e-3   -2.13%        1.21e-3   -1.37%
map/itraverse/itraverse                   1.23e-3   1.20e-3   -2.60%        1.21e-3   -1.39%
map/itraverse/itraverse/lens              1.23e-3   1.20e-3   -2.45%        1.21e-3   -1.56%
map/itraverse/itraversed                  1.21e-3   1.20e-3   -1.22%        1.21e-3   -0.45%
map/itraverse/itraversed/lens             1.22e-3   1.20e-3   -1.49%        1.21e-3   -0.26%
map/itraverse/native                      1.24e-3   1.20e-3   -3.20%        1.21e-3   -2.36%
map/map/each                              3.98e-4   3.85e-4   -3.31%        3.87e-4   -2.71%
map/map/each/lens                         4.50e-4   4.59e-4   +2.13%        4.62e-4   +2.84%
map/map/imapped                           4.42e-4   4.60e-4   +4.25%        4.61e-4   +4.38%
map/map/imapped/lens                      4.45e-4   4.61e-4   +3.54%        4.61e-4   +3.49%
map/map/itraversed                        4.56e-4   4.59e-4   +0.68%        4.62e-4   +1.19%
map/map/itraversed/lens                   4.49e-4   4.60e-4   +2.37%        4.62e-4   +2.91%
map/map/native                            4.69e-4   4.60e-4   -1.87%        4.62e-4   -1.47%
map/partsOf/ipartsOf                      4.12e-3   4.01e-3   -2.49%        4.07e-3   -1.08%
map/partsOf/ipartsOf/lens                 9.94e-3   9.96e-3   +0.13%        1.01e-2   +1.42%
map/partsOf/partsOf                       2.89e-3   2.88e-3   -0.47%        2.93e-3   +1.23%
map/partsOf/partsOf/lens                  1.06e-2   1.07e-2   +0.66%        1.09e-2   +2.38%
map/singular/singular                     1.70e-3   1.70e-3   -0.06%        1.72e-3   +1.30%
map/singular/singular/lens                7.81e-3   7.86e-3   +0.71%        8.04e-3   +3.02%
map/traverse/each                         1.12e-3   1.07e-3   -3.98%        1.08e-3   -3.47%
map/traverse/each/lens                    1.09e-3   1.07e-3   -2.05%        1.08e-3   -1.25%
map/traverse/itraversed                   1.12e-3   1.08e-3   -3.79%        1.08e-3   -3.58%
map/traverse/itraversed/lens              1.13e-3   1.10e-3   -2.24%        1.11e-3   -1.28%
map/traverse/native                       1.10e-3   1.06e-3   -3.28%        1.08e-3   -2.04%
misc/adjoin/adjoin                        6.45e-8   6.03e-8   -6.44%        6.05e-8   -6.10%
misc/adjoin/adjoin/lens                   3.50e-6   3.55e-6   +1.19%        3.57e-6   +1.85%
misc/adjoin/hand-written                  2.87e-8   2.91e-8   +1.67%        2.92e-8   +1.99%
sequence/elements/elements                1.28e-3   1.27e-3   -0.54%        1.26e-3   -1.63%
sequence/elements/elements/lens           1.92e-3   1.92e-3   +0.29%        1.90e-3   -0.84%
sequence/elements/itraversed              2.33e-4   2.28e-4   -2.19%        2.26e-4   -3.14%
sequence/elements/itraversed/lens         5.34e-4   6.00e-4  +12.30%        5.99e-4  +12.20%
sequence/imap/each                        2.62e-4   2.28e-4  -12.77%        2.27e-4  -13.38%
sequence/imap/imap                        2.42e-4   2.29e-4   -5.35%        2.26e-4   -6.57%
sequence/imap/imap/lens                   2.42e-4   2.27e-4   -6.42%        2.26e-4   -6.59%
sequence/imap/imapped                     2.43e-4   2.27e-4   -6.77%        2.26e-4   -6.96%
sequence/imap/imapped/lens                2.43e-4   2.26e-4   -6.76%        2.27e-4   -6.57%
sequence/imap/itraversed                  2.43e-4   2.29e-4   -5.53%        2.26e-4   -6.63%
sequence/imap/itraversed/lens             5.49e-4   5.39e-4   -1.68%        5.35e-4   -2.58%
sequence/imap/native                      2.42e-4   2.28e-4   -5.79%        2.23e-4   -7.93%
sequence/indices/indices                  5.84e-4   5.65e-4   -3.27%        5.64e-4   -3.35%
sequence/indices/indices/lens             5.82e-4   5.64e-4   -3.05%        5.66e-4   -2.80%
sequence/itraverse/each                   4.59e-3   4.75e-3   +3.47%        4.67e-3   +1.74%
sequence/itraverse/itraverse              4.55e-3   4.69e-3   +3.24%        4.54e-3   -0.14%
sequence/itraverse/itraverse/lens         4.49e-3   4.66e-3   +3.96%        4.58e-3   +2.14%
sequence/itraverse/itraversed             4.47e-3   4.69e-3   +4.87%        4.58e-3   +2.31%
sequence/itraverse/itraversed/lens        4.49e-3   4.71e-3   +4.98%        4.60e-3   +2.36%
sequence/itraverse/native                 4.50e-3   4.64e-3   +3.21%        4.57e-3   +1.56%
sequence/map/each                         2.06e-4   2.19e-4   +6.46%        2.19e-4   +6.32%
sequence/map/each/lens                    2.07e-4   2.18e-4   +5.23%        2.18e-4   +5.55%
sequence/map/imapped                      2.06e-4   2.21e-4   +7.27%        2.19e-4   +6.41%
sequence/map/imapped/lens                 2.07e-4   2.21e-4   +7.03%        2.19e-4   +5.68%
sequence/map/itraversed                   2.06e-4   2.21e-4   +7.49%        2.19e-4   +6.30%
sequence/map/itraversed/lens              2.11e-4   2.30e-4   +8.94%        2.28e-4   +8.12%
sequence/map/native                       2.05e-4   2.19e-4   +6.72%        2.17e-4   +5.76%
sequence/partsOf/ipartsOf                 3.34e-3   3.27e-3   -2.04%        3.31e-3   -0.79%
sequence/partsOf/ipartsOf/lens            1.36e-2   1.39e-2   +2.14%        1.37e-2   +0.76%
sequence/partsOf/partsOf                  2.08e-3   2.13e-3   +2.30%        2.11e-3   +1.68%
sequence/partsOf/partsOf/lens             6.62e-3   6.85e-3   +3.49%        6.94e-3   +4.87%
sequence/singular/singular                1.62e-3   1.63e-3   +0.75%        1.62e-3   +0.24%
sequence/singular/singular/lens           7.25e-3   7.69e-3   +6.10%        7.33e-3   +1.01%
sequence/traverse/each                    1.10e-3   1.10e-3   +0.36%        1.09e-3   -1.37%
sequence/traverse/each/lens               1.10e-3   1.10e-3   +0.60%        1.09e-3   -0.85%
sequence/traverse/itraversed              1.09e-3   1.10e-3   +0.78%        1.08e-3   -0.81%
sequence/traverse/itraversed/lens         1.10e-3   1.11e-3   +0.57%        1.09e-3   -1.49%
sequence/traverse/native                  1.12e-3   1.11e-3   -1.04%        1.09e-3   -2.74%
unboxed-vector/imap/each                  3.36e-4   3.44e-4   +2.54%        3.41e-4   +1.52%
unboxed-vector/imap/native                3.41e-4   3.45e-4   +1.24%        3.39e-4   -0.66%
unboxed-vector/map/each                   3.34e-4   3.37e-4   +0.88%        3.33e-4   -0.55%
unboxed-vector/map/each/lens              3.34e-4   3.36e-4   +0.63%        3.31e-4   -0.95%
unboxed-vector/map/native                 3.29e-4   3.38e-4   +2.72%        3.34e-4   +1.50%
vector/elements/elements                  2.27e-4   2.31e-4   +2.10%        2.25e-4   -0.75%
vector/elements/elements/lens             4.93e-4   5.00e-4   +1.34%        4.88e-4   -1.14%
vector/elements/itraversed                1.20e-4   1.21e-4   +0.55%        1.18e-4   -1.33%
vector/elements/itraversed/lens           1.20e-4   1.22e-4   +1.42%        1.18e-4   -1.95%
vector/imap/each                          1.24e-4   1.25e-4   +0.15%        1.23e-4   -0.91%
vector/imap/imap                          1.23e-4   1.23e-4   -0.60%        1.23e-4   -0.03%
vector/imap/imap/lens                     1.27e-4   1.42e-4  +11.82%        1.26e-4   -0.98%
vector/imap/imapped                       1.25e-4   1.25e-4   +0.30%        1.23e-4   -1.01%
vector/imap/imapped/lens                  1.25e-4   1.24e-4   -0.32%        1.24e-4   -1.06%
vector/imap/itraversed                    1.21e-4   1.20e-4   -0.74%        1.19e-4   -1.94%
vector/imap/itraversed/lens               1.22e-4   1.23e-4   +0.91%        1.32e-4   +7.56%
vector/imap/native                        1.20e-4   1.20e-4   -0.07%        1.19e-4   -0.83%
vector/indices/indices                    3.41e-4   3.50e-4   +2.52%        3.44e-4   +0.77%
vector/indices/indices/lens               1.15e-4   1.18e-4   +2.72%        1.16e-4   +1.10%
vector/itraverse/each                     1.23e-3   1.25e-3   +2.18%        1.23e-3   +0.04%
vector/itraverse/itraverse                1.23e-3   1.24e-3   +0.80%        1.22e-3   -0.48%
vector/itraverse/itraverse/lens           1.42e-3   1.42e-3   -0.29%        1.41e-3   -0.54%
vector/itraverse/itraversed               1.23e-3   1.24e-3   +1.19%        1.22e-3   -0.34%
vector/itraverse/itraversed/lens          1.42e-3   1.41e-3   -0.55%        1.40e-3   -1.05%
vector/itraverse/native                   1.50e-3   1.48e-3   -1.03%        1.47e-3   -1.71%
vector/map/each                           1.15e-4   1.14e-4   -0.70%        1.14e-4   -0.92%
vector/map/each/lens                      1.25e-4   1.23e-4   -1.65%        1.23e-4   -2.17%
vector/map/imapped                        1.16e-4   1.16e-4   -0.06%        1.14e-4   -1.33%
vector/map/imapped/lens                   1.21e-4   1.20e-4   -0.38%        1.19e-4   -1.79%
vector/map/itraversed                     1.16e-4   1.16e-4   -0.14%        1.14e-4   -1.18%
vector/map/itraversed/lens                1.15e-4   1.15e-4   +0.55%        1.14e-4   -0.35%
vector/map/native                         1.15e-4   1.15e-4   -0.23%        1.14e-4   -0.56%
vector/partsOf/ipartsOf                   2.18e-3   2.26e-3   +3.83%        2.23e-3   +2.18%
vector/partsOf/ipartsOf/lens              6.68e-3   6.72e-3   +0.62%        6.69e-3   +0.12%
vector/partsOf/partsOf                    1.20e-3   1.28e-3   +6.02%        1.27e-3   +5.14%
vector/partsOf/partsOf/lens               5.48e-3   5.59e-3   +1.91%        5.51e-3   +0.55%
vector/singular/singular                  6.78e-4   6.06e-4  -10.64%        5.92e-4  -12.67%
vector/singular/singular/lens             3.80e-3   3.94e-3   +3.74%        3.87e-3   +1.92%
vector/traverse/each                      9.54e-4   9.20e-4   -3.62%        9.47e-4   -0.78%
vector/traverse/each/lens                 1.12e-3   1.12e-3   -0.51%        1.13e-3   +0.95%
vector/traverse/itraversed                9.27e-4   9.20e-4   -0.69%        9.18e-4   -0.90%
vector/traverse/itraversed/lens           9.35e-4   9.47e-4   +1.39%        9.24e-4   -1.09%
vector/traverse/native                    9.43e-4   9.39e-4   -0.41%        9.50e-4   +0.75%

zzz-geom-mean                             7.03e-4   7.02e-4   -0.10%        7.02e-4   -0.19%
```

In general, it's all noise, however

`bytestring` changes I don't understand. They **should not** be affected.

```
bytestring/imap/bytes                     4.67e-5   6.94e-5  +48.56%        7.03e-5  +50.44%
bytestring/imap/bytes/lens                4.65e-5   6.92e-5  +48.80%        7.01e-5  +50.59%
bytestring/map/each/lens                  4.64e-5   3.75e-5  -19.17%        3.75e-5  -19.24%
```

This is due forgotten `{-# INLINE #-}`

```
sequence/elements/itraversed/lens         5.34e-4   6.00e-4  +12.30%        5.99e-4  +12.20%
sequence/imap/each                        2.62e-4   2.28e-4  -12.77%        2.27e-4  -13.38%
```

Here `lens` benefits from better `Vector` instance

```
vector/imap/imap/lens                     1.27e-4   1.42e-4  +11.82%        1.26e-4   -0.98%
```

So in general, I don't see a reason to not proceed with `with-index`.

**Comment by ekmett** [comment]
All right, Oleg. I trust you. Let's go for it.

**Comment by arybczak** [comment]
Looks good, let's do it :tada:

**Comment by RyanGlScott** [comment]
Is the plan to include [the patch from here](https://github.com/phadej/with-index/blob/06e5758f553b427405653dbca331545c2bbdcbd6/patches/lens.patch) in this PR before merging? Or are you planning to merge this first, and then bring in that patch in a separate PR?

Either way, I humbly request that you update the `CHANGELOG` to mention how existing instances should migrate their code.

**Comment by RyanGlScott** [comment]
Also, there's one more thing worth considering before charging forward: the name "`with-index`" is [already taken on Hackage](http://hackage.haskell.org/package/with-index).

**Comment by phadej** [comment]
Let's merge this now, and I'll follow-up with new package in another PR. This is the real breaking change, moving code around into another package is less so (though breaking as well for people defining instances from `lens` and `optics`).

Argh. Alternative package name ideas are welcome. I'll try to think something myself, `traversable-with-index` is an option, e.g.

**Comment by phadej** [comment]
After hard hard thinking, I have only two options `traversable-with-index` and `keys-fd`. Even the first one is mouthful, it is less confusing for people not verse in Hackage-package-history.

**Comment by RyanGlScott** [comment]
> Let's merge this now, and I'll follow-up with new package in another PR.

Sounds good to me.

> Argh. Alternative package name ideas are welcome.

Hm. `traversable-with-index` is a bit of a mouthful, and especially so for `traversable-with-index-instances`. As far as alternative names go, my initial gut reaction was `indexes`, in the same spirit as `keys`. But perhaps that's too easily confused with existing packages like `indexed`. Some other possibilities are `indexed-traversable` are `indexed-classes`.

**Comment by phadej** [comment]
```
indexed-traversable
traversable-with-index
```

I'm not sure that saving 3 characters helps here :) (though yes, two words is better than three).

Just `itraverse` as package name is another option.

**Comment by phadej** [comment]
@RyanGlScott so I'm fine with either of three

```
indexed-traversable
traversable-with-index
itraverse
```

(`indexed-classes` feels too unprecise). Ack which one you'd like the most, and let's go with it.

**Comment by arybczak** [comment]
I like `indexed-traversable` :slightly_smiling_face:

**Pull request merged**
