### PR TITLE
Improve indexed instances for Seq

### PR DESCRIPTION
**Pull request by treeowl**
Make imap, ifoldr, ifoldl, ifoldMap, and itraverse
use native operations from Data.Sequence.

### CODE REVIEW

**Comment by treeowl** [comment]
The failure in 8.0 looks like a cabal issue somewhere.

**Comment by RyanGlScott** [comment]
Specifically, it's an issue wherein hvr's Ubuntu PPA's build of GHC 8.0.1-rc1 was built with a version of `Cabal` that is [out-of-sync](https://github.com/haskell/cabal/issues/2114#issuecomment-172876949) with the same PPA's build of `cabal-install-1.24`, so this issue should (eventually) take care of itself once newer versions are built.

**Comment by hvr** [comment]
@RyanGlScott fwiw, I just uploaded new ppa snapshots of GHC 8.0 & cabal-install... so this problem will hopefully  resolve in a few hours...

**Comment by hvr** [comment]
@treeowl 

> The failure in 8.0 looks like a cabal issue somewhere.

I've retriggered a rebuild, GHC 8.0 is green now

**Comment by RyanGlScott** [comment]
LGTM.

(See also #629, where making the default implementation of `itraverse` be `Data.Sequence.traverseWithIndex` in the future is discussed.)

**Pull request merged**
