### PR TITLE
allow filepath version < 1.6

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
There is a new major version of filepath 1.5.0.0.

Tested and seemed to build fine.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
I'm unable to test this at the moment, since `hashable` doesn't yet build with `filepath-1.5.*`. I'd prefer to wait until https://github.com/haskell-unordered-containers/hashable/pull/290 lands before proceeding.

**Comment by ysangkok** [comment]
@RyanGlScott a new hashable is now out with filepath-1.5 support: https://hackage.haskell.org/package/hashable-1.4.4.0/changelog

**Comment by RyanGlScott** [comment]
Great!

However, since I've last viewed this, the changes from #1060 have been folded into this PR. This feels odd, as #1060 doesn't really have anything to do with the stated purpose of this PR. @BebeSparkelSparkel, can you revert the #1060-related changes so that we can handle them separately?

**Comment by RyanGlScott** [comment]
Superseded by #1064.

**Pull request closed without merging**
