### PR TITLE
Profunctor conversions

### PR DESCRIPTION
**Pull request by phadej**
Follow up to #922

### CODE REVIEW

**Comment by guaraqe** [comment]
Nice! The type `WrappedPafb` now appears on the type signatures, maybe it should be exported too?

**Comment by phadej** [comment]
@guaraqe good point. I'll put it into `.Internal` module.

**Comment by phadej** [comment]
@guaraqe any further comments?

**Comment by guaraqe** [comment]
No, looks good to me. Thank you!

**Comment by phadej** [comment]
TODO: add changelog

**Pull request merged**
