### PR TITLE
Add 'traversal'

### PR DESCRIPTION
**Pull request by ChrisPenner**
Hi everyone!

I'll start by expressing I'm aware of the [Fairbairn Threshold](https://wiki.haskell.org/Fairbairn_threshold) and I'm also aware that this proposal doesn't add any *technical* value to the library; the value of this addition is entirely in providing more **discoverability**, **API consistency**, and **documentation**.

The proposal is to add the following combinator to `Control.Lens.Traversal`.

```haskell
traversal :: (forall f. Applicative f => (a -> f b) -> s -> f t)
          -> Traversal s t a b
traversal t f s = t f s
```

( I tried `traversal = id` but the type-checker was upset with me, if you have an idea on fixing it let me know)

The reasoning is as follows; beginners craft most of their optics using the provided helpers. E.g. when they need something which the TH helpers can't provide they reach for `lens`, `prism`, or `iso` which provide a concrete **signature** for creating the thing they want, alongside **documentation** on how to use the helper. Each of these things are crucial to beginners who don't yet know or understand the underlying constructions behind optics.

However, when the beginner realizes they need a custom traversal to accomplish their goal, they naturally search for the corresponding `traversal` helper which is strangely missing! The beginner is bewildered by this inconsistency because they **simply don't know** that you can construct traversals without a helper; and they **don't know** the signature they'd need in order to do so. In fact, the signature they'd need to write is deliberately hidden from them behind the `Traversal` type synonyms. The beginner is now confused and annoyed, and will likely give up and go do something else, cursing the complexity of `lens` under their breath.

I dearly hope I don't need to explain why a beginner's first impressions and first experiences are important, but if you'd like me to hop on my soapbox I'll gladly do so 😄 

## Benefits
* Adding `traversal` establishes consistency with `lens`, `prism` and `iso`
* It provides a findable (via hoogle and intuition) home for haddocks which explain the intricacies of writing your own traversals, how to do so, examples, of same, and even why the `traversal` helper is actually redundant and unnecessary.

## Concerns
* Introducing a new export may conflict with user code. A [best effort search of all of hackage](https://codesearch.aelve.com/haskell/search?query=traversal%20%3A%3A&filter=Control.Lens&insensitive=off&space=on&precise=on&sources=on) reveals only a few occurrences of `traversal`; only two of which are exported, once by `mezzolens` which is another optics library (and therefore is unlikely to ever conflict) and once [here](https://hackage.haskell.org/package/references-0.3.3.1/docs/Control-Reference-Generators.html#v:traversal) which already must be imported qualified when using with `lens` due to other conflicts; therefore suspect this is a non-issue.
* "This doesn't add any technical value"; this is true, but there are many other types of value which it **does** add, namely: discoverability, consistency, documentation, and improved developer experience.

Lastly I'll bring up the existence of `%%~` which interestingly is also defined as `id`. Its simple definition suggests it was added for the same reasons which I suggest we add `traversal`: for consistency with the rest of `lens` and as a learning tool. 

I believe that `traversal` fulfills a different role than `%%~` and argue that the existence of `%%~` in no way reduces the need for `traversal`.

---

I'm not a performance expert, if there's a re-write rule or pragma I can add to "magic it all away to nothing" please inform me 😄

### CODE REVIEW

**Comment by phadej** [comment]
FWIW, we have `traverseOf` even mostly you could just use nothing at all too. So having `traversal` for documentation purposes is :+1:

**Comment by phadej** [comment]
- HLint fails.
- Also there is no tests using `traversal` (e.g. no doctests).
- I'm not sure, but I suspect that

```haskell
traversal :: (a -> f b) -> s -> f t) -> LensLike f s t a b
```

would be type-inference-wise better signature, it's rank-1 (Compare to the signature of `traverseOf`).

**Comment by RyanGlScott** [comment]
Sorry for taking so long to look at this. This seems like a worthwhile addition. Would you mind rebasing this on top of the latest `master` to get CI unstuck?

**Comment by ChrisPenner** [comment]
@RyanGlScott  Rebased 😄

**Review by phadej — CHANGES_REQUESTED** [review]
Still no tests, nor change in the signature.

**Comment by RyanGlScott** [comment]
In the interest of moving this across the finish line, I've pushed the recommend type signature change, along with a handful of doctests. I'm not sure if these are the kind of tests you had in mind, so if not, let me know.

**Pull request merged**
