### PR TITLE
Extract template haskell

### PR DESCRIPTION
**Pull request by glguy**
See #844 for current discussion. Don't merge this until we're ready with a release of `template-haskell-lens`

### CODE REVIEW

**Comment by RyanGlScott** [comment]
A couple of remarks:

* This branch appears to have an extra `Add gplate1` commit, except that it's different from the one that's currently in `master`. Can this branch be rebased on top of `master` to avoid this? Otherwise, it makes looking at the diff noisier than it should be.
* This goes a bit beyond what I originally imagined and not only removes `Language.Haskell.TH.Lens`, but also `Control.Lens.TH`. Personally, I only desire to package up `Language.Haskell.TH.Lens` separately simply because its API changes so frequently to keep in sync with `template-haskell` changes. On the other hand, `Control.Lens.TH` is quite stable, so I don't think the same argument applies there. What do you think?

**Comment by phadej** [comment]
I also had only splitting out the `Language.Haskell.TH.Lens`.

`Control.Lens.TH` does use `Language.Haskell.TH.Lens`, but only a small portion (at least not many top level identifiers)

```
    • Variable not in scope:
        substType :: Map k0 Type -> [Type] -> [Type]
    • Perhaps you want to add ‘substType’ to the import list
      in the import of ‘Language.Haskell.TH.Lens’
      (src/Control/Lens/TH.hs:119:1-34).
    |
524 |         substType (Map.fromList $ zip vars tys) args
    |         ^^^^^^^^^

src/Control/Lens/TH.hs:535:29: error:
    • Variable not in scope: typeVars :: Getting (Set a) [Type] a
    • Perhaps you want to add ‘typeVars’ to the import list
      in the import of ‘Language.Haskell.TH.Lens’
      (src/Control/Lens/TH.hs:119:1-34).
    |
535 |       vars = toList $ setOf typeVars args
    |                             ^^^^^^^^

src/Control/Lens/TH.hs:566:40: error:
    • Variable not in scope:
        conFields
          :: (s0 -> Const (Endo [Type]) t0) -> Con -> Const (Endo [Type]) Con
    • Perhaps you want to add ‘conFields’ to the import list
      in the import of ‘Language.Haskell.TH.Lens’
      (src/Control/Lens/TH.hs:119:1-34).
    |
566 |                 , [field] <- toListOf (conFields._2) con
    |                                        ^^^^^^^^^

src/Control/Lens/TH.hs:577:29: error:
    • Variable not in scope: name :: Getting b TyVarBndr b
    • Perhaps you meant data constructor ‘Name’ (imported from Language.Haskell.TH.Syntax)
      Perhaps you want to add ‘name’ to the import list in the import of
      ‘Language.Haskell.TH.Lens’ (src/Control/Lens/TH.hs:119:1-34).
    |
577 |    let typeArgs = map (view name) (dataParameters dataDecl)
    |                             ^^^^

src/Control/Lens/TH.hs:581:14: error:
    • Variable not in scope:
        substTypeVars :: Map Name Name -> [b0] -> [Name]
    • Perhaps you want to add ‘substTypeVars’ to the import list
      in the import of ‘Language.Haskell.TH.Lens’
      (src/Control/Lens/TH.hs:119:1-34).
    |
581 |      return (substTypeVars m typeArgs)
    |              ^^^^^^^^^^^^^

src/Control/Lens/TH.hs:605:22: error:
    • Variable not in scope: name :: Getting t Con t
    • Perhaps you meant data constructor ‘Name’ (imported from Language.Haskell.TH.Syntax)
      Perhaps you want to add ‘name’ to the import list in the import of
      ‘Language.Haskell.TH.Lens’ (src/Control/Lens/TH.hs:119:1-34).
    |
605 |   let conName = view name con
    |                      ^^^^

src/Control/Lens/TH.hs:606:27: error:
    • Variable not in scope:
        typeVars :: Getting (Endo [a]) [TyVarBndr] a
    • Perhaps you want to add ‘typeVars’ to the import list
      in the import of ‘Language.Haskell.TH.Lens’
      (src/Control/Lens/TH.hs:119:1-34).
    |
606 |   let typeArgs = toListOf typeVars (dataParameters dataDecl)
```

**Comment by glguy** [comment]
> A couple of remarks:
> 
> * This branch appears to have an extra `Add gplate1` commit, except that it's different from the one that's currently in `master`. Can this branch be rebased on top of `master` to avoid this? Otherwise, it makes looking at the diff noisier than it should be.

That was a mistake.

> * This goes a bit beyond what I originally imagined and not only removes `Language.Haskell.TH.Lens`, but also `Control.Lens.TH`. Personally, I only desire to package up `Language.Haskell.TH.Lens` separately simply because its API changes so frequently to keep in sync with `template-haskell` changes. On the other hand, `Control.Lens.TH` is quite stable, so I don't think the same argument applies there. What do you think?

But if everyone wants to keep half the TH stuff around and only drop the `Language.Haskell.TH.Lens` module into its own project I'm fine with that. I just misunderstood the goal. I think the fact that `Control.Lens.TH` is so easily separable might be a good argument for its removal. It would allow us to drop at least the `th-abstraction` dependency for people who don't need it. It would also potentially allow the `Control.Lens.TH` module to be cleaned up to use actual Template Haskell in its implementation. The current `Name` construction is an unfortunate hack and some of the other implementation would be nicer, I think, if it was able to actually use splices.

I'm in favor of making `lens` as small as it can be. For a lot of uses the TH modules aren't needed. We had luck shaving off dependencies like `aeson` and this just seemed like a chance to go further.

**Comment by phadej** [comment]
`th-abstraction` is a dependency of e.g. `bifunctors`, so dropping it is pointless.

**Comment by phadej** [comment]
@glguy if you'd like to split the `Control.Lens.TH` out too, then it would go into `lens-th` package :) 

I'm not against that either.

However, `template-haskell-lens` is currently a priority for GHC-8.8

**Pull request closed without merging**
